// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
// export const metadata: Metadata = {
//   title: "Mamar",
//   description: "Generated by ahruf",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={` bg-[#F4F8F7] ${inter.variable}  antialiased`}>
//         {children}
//       </body>
//     </html>
//   );
// }
   




import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "MARMAR - Medication Alert and Risk Management",
  description: "MARMAR empowers you with knowledge to manage your medications safely. Our AI-driven platform analyzes drug interactions, provides personalized advice, and helps prevent adverse effects.",
  keywords: ["medication management", "drug interactions", "medication safety", "prescription management", "polypharmacy", "health tech", "patient safety"],
  authors: [{ name: "MARMAR Team" }],
  openGraph: {
    title: "MARMAR - Smart Medication Safety Platform",
    description: "Take control of your health with MARMAR's AI-powered medication analysis. Prevent adverse drug interactions and manage your prescriptions safely.",
    url: "https://marmar.life",
    siteName: "MARMAR",
    images: [
      {
        url: "https://marmar.life/og-image.png",
        width: 1200,
        height: 630,
        alt: "MARMAR - Medication Management Platform",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MARMAR - Medication Safety Assistant",
    description: "AI-driven medication analysis for safer health management.",
    creator: "@marmarapp",
  },
  viewport: "width=device-width, initial-scale=1",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: "https://marmar.life",
  },
};

// Structured data for landing page
const structuredData = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "MARMAR",
  "url": "https://marmar.life",
  "logo": "https://marmar.life/logo.png",
  "description": "MARMAR provides AI-powered medication analysis to prevent adverse drug interactions and improve medication safety.",
  "sameAs": [
    "https://twitter.com/marmarapp",
    "https://www.linkedin.com/company/marmarapp/",
    "https://www.instagram.com/marmarapp/"
  ],
  "offers": {
    "@type": "Offer",
    "description": "Access MARMAR's medication analysis platform",
    "url": "https://app.marmar.life"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        <meta name="theme-color" content="#66B29B" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="preconnect" href="https://app.marmar.life" />
      </head>
      <body className={`bg-[#F4F8F7] ${inter.variable} antialiased`}>
        {children}
        
        {/* Analytics script */}
        <Script 
          src="https://scripts.simpleanalyticscdn.com/latest.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}